"""Remote data asset registry (auto-generated by data_registry.py).

Do not edit manually.  Re-run ``scripts/data_registry.py generate``
to update after uploading new data.
"""

CACHE_DIR_NAME = "copykat_py"

REGISTRY: dict[str, dict[str, str]] = {
    "exp_rawdata.tsv.gz": {
        "url": "https://zenodo.org/records/19558066/files/exp_rawdata.tsv.gz?download=1",
        "sha256": "f8dfc96ea15bcef74e97a6ca08c676eb547a356c34d209a825425c4d0cf821c8",
    },
}
